### PR TITLE
Convert to .NET Standard 2.1 and .NET Core 3.1

### PR DESCRIPTION
**Pull request by y2k4life**

### CODE REVIEW

**Comment by y2k4life** [comment]
I think one issue might be the license file which at one point you did as well. I wanted to make sure that is my branch was cloned the credit went to where it goes. I copied it out of the code and it appears to have changed.

**Comment by y2k4life** [comment]
Two other piece that changed. One is a duplicate of the bug fix in my previous pull request and there was some issues with Entity Framework and the custom validation that I removed.

**Comment by Daniel-Miller** [comment]
Thanks for your improvements here - these look great! Another reader mentioned me to add a license file, so I added the standard MIT license. I will remove the 'extra' Timeline/LICENSE file.

**Comment by znamenap** [comment]
Hi @y2k4life and @Daniel-Miller, since Daniel have invested the effort on minmised set of dependencies and langugare traits, converting the project just to the .NETStandard and .NET Core 3.1 is truly benefitial, nevertheless, it is only benefitial to new applications developed in the near future or close presence. There are also applications what cannot be simply upgraded to .NET Core simply or because of dependencies.
Could you consider the fact there could be multi-targeted result for more runtimes? The example of using the shared project in example at https://www.codeproject.com/Tips/5268256/NET-Standard-What-are-the-Alternatives. If you wish I can also join and try to help with it.
Otherwise very good job!

Pavel

**Comment by y2k4life** [comment]
Pavel,

Thank you. My understanding is that this project has only one project `Timeline`. The other projects are sample implementations of the one project. From reviewing the code `Timeline` has no platform specific dependencies. It actually has no dependencies. Reading the article the following paragraph points out the caveat of using .NET Standard which does not apply to `Timeline`.

> That is good if your code is really generic, for example if you create a client package or implement a math model. **However, once some code or NuGet Package has a dependency on some specific platform, .NET Standard is not going to be helpful**. .NET Standard is standard, not platform specific. So how to target multiple platforms in such a situation?

The other projects might fall into a situation where .NET Standard does not work, but those projects,  should not be used in real world implementation. As it stands right now even those projects, which do depend on other NuGet Packages, don't rely on anything platform specific. All of the dependencies are .NET Standard as well.

The only change that would broaden the compatible platforms, .NET Framework, is to use 2.0 instead of 2.1 [.NET Standard](https://dotnet.microsoft.com/platform/dotnet-standard). The best option is to target .NET Standard 1.1 but anything before 2.0 would require some rewrites due to the use of `System.Runtime.Serialization` and `Tuple`. The serialization might not be as much of an issue, used mainly for exceptions, as the use of Tuples.

Another possible mitigating factor is that `Timeline` would not be used in a current (legacy) project, but one that is a new project. I would argue that most new projects would use .NET Core and the secondary choice is .NET Framework. If the choice is .NET Framework then changing to .NET Standard 2.0 would be a better fit.

My mindset was the newest is the best but with .NET Standard it is the oldest that works is the best. 😁🤦‍♂️

**Comment by Daniel-Miller** [comment]
My experience with .NET Standard and .NET Core is limited, so I cannot speak with any authority here, but I will share a quick (entirely personal and subjective) opinion:

Looking at the projects now, post-upgrade to .NET Standard and .NET Core, the project files (.csproj) are simpler and more compact, and Visual Studio provides a more streamlined view of dependencies (which are few to none, by design). This is very much in alignment with the philosophical priorities driving the development of the code in this repository.

"Simplify, then add lightness," as Colin Chapman was famous for saying. :sunglasses:

@y2k4life could you comment on how easy (or difficult) it is to use a .NET Standard class library assembly in a .NET Framework application? My understanding is a .NET Framework **application assembly** can reference .NET Standard **library assembly** without issue, but my understanding is anectodal only.

**Comment by y2k4life** [comment]
[.NET Standard](https://dotnet.microsoft.com/platform/dotnet-standard)

The reason I make the suggestion to change the `TargetFramework` to `netstandard2.0` is because as of now you can't use `Timeline` in .NET Framework. Once that change is made, adding a reference would be no different, regardless if `Timeline` is a project in the solution with .NET Framework or a NugetPackage. The only issue is that the .NET Framework has to be 4.6.1 or greater.

This website linked above has a chart where you pick the version of .NET Standard that will then show the compatible platforms an the respective versions of the platform. If you change the pull down to 2.1 you will see there are no compatible .NET Frameworks. Furthermore if you choose 1.1 it covers more platforms, going all the way back to .NET Framework 4.5. The question as I posed in my last post, would the older platforms be used or only newer ones?

I could easily remove the `Serialization` from the exceptions and turn the `Tuple` into a first class object. Then it could target 1.1.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
</Project>
```

**Comment by Daniel-Miller** [comment]
Whenever I build a new .NET Framework application I always use the latest .NET Framework version, and whenever I inherit a .NET Framework application from another developer the first thing I do is upgrade the projects in the solution to the latest .NET Framework version. 

Today that is 4.8.0, therefore I think it is very reasonable to require .NET Framework 4.6.1 or higher, so targeting .NET Standard 2.0 is an ideal choice for my needs. 

Unfortunately I cannot (yet) escape .NET Framework applications entirely!

**Comment by y2k4life** [comment]
Maybe .NET 5.0? I always love a challenge and took it upon myself to move the code to .NET Standard 1.2. There are some other challenges I did not see at first. One, which I was able to rewrite, was the `Apply` method. That uses reflections to find the proper `When` method. Unfortunately `GetMethod` is not available, but I was able to rewrite the logic with `GetType().GetTypeInfo().GetDeclaredMethods("When")` and then iterate over the methods to find one with the correct parameter. Another issue which was not avoidable was `Timer` used in the `Cache`. I reviewed the `Applies To` section of the reference for `Timer` and found that it applies to .NET Standard 1.2. Other than that I removed the `Serialization` on the exceptions. Along with creating `EventOverrideKey` and `CommandOverrideKey` to be used instead of a tuple. I'm testing now and should have this ready soon.

Was there a purpose for the `Exceptions` being `Serializable`?

**Comment by Daniel-Miller** [comment]
I have done some reading today on the topic and I think you're right: maybe .NET 5.0. Microsoft says no "Core" and no "Framework" in .NET 5, so I guess we'll discover exactly what that means later this year.

I am never entirely happy with the idea of using reflection at run-time, so your changes to find the proper `When` method are almost certainly an improvement. Even so, I'd still like to find some way of achieving the same end result using native C# code that the compiler is able to check. (I have seen various solutions using IoC containers, but in this particular instance I'd prefer to steer clear of those also.)

There was no purpose for serializable `Exceptions`. Visual Studio must have made them `Serializable` when it generated the `Exception` classes for me, because that was not an intentional design decision on my part.

**Pull request merged**
